In [58]:
import numpy as np 
import pandas as pd 
import requests

In [59]:
url = "https://api.worldbank.org/countries?format=json&per_page=300"

response = requests.get(url)
response.status_code

200

In [60]:
data = response.json()
print(data)

[{'page': 1, 'pages': 1, 'per_page': '300', 'total': 296}, [{'id': 'ABW', 'iso2Code': 'AW', 'name': 'Aruba', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Oranjestad', 'longitude': '-70.0167', 'latitude': '12.5167'}, {'id': 'AFE', 'iso2Code': 'ZH', 'name': 'Africa Eastern and Southern', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'AFG', 'iso2Code': 'AF', 'name': 'Afghanistan', 'region': {'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Middle East, North Africa, Afghanistan & Pakistan'}, 'adminregion': {'id': 'MNA', 'iso2code': 'XQ', 'value': 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Kabul', 'longitude': '69.1761', 'latitude': '34.5228'}, {'id': 'AFR', 'iso2Code': 'A9', 'name': 'Africa', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'AFW', 'iso2Code': 'ZI', 'name': 'Africa Western and Central', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'AGO', 'iso2Code': 'AO', 'name': 'Angola', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Luanda', 'longitude': '13.242', 'latitude': '-8.81155'}, {'id': 'ALB', 'iso2Code': 'AL', 'name': 'Albania', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Tirane', 'longitude': '19.8172', 'latitude': '41.3317'}, {'id': 'AND', 'iso2Code': 'AD', 'name': 'Andorra', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Andorra la Vella', 'longitude': '1.5218', 'latitude': '42.5075'}, {'id': 'ARB', 'iso2Code': '1A', 'name': 'Arab World', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'ARE', 'iso2Code': 'AE', 'name': 'United Arab Emirates', 'region': {'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Middle East, North Africa, Afghanistan & Pakistan'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Abu Dhabi', 'longitude': '54.3705', 'latitude': '24.4764'}, {'id': 'ARG', 'iso2Code': 'AR', 'name': 'Argentina', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': 'LAC', 'iso2code': 'XJ', 'value': 'Latin America & Caribbean (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Buenos Aires', 'longitude': '-58.4173', 'latitude': '-34.6118'}, {'id': 'ARM', 'iso2Code': 'AM', 'name': 'Armenia', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Yerevan', 'longitude': '44.509', 'latitude': '40.1596'}, {'id': 'ASM', 'iso2Code': 'AS', 'name': 'American Samoa', 'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Pago Pago', 'longitude': '-170.691', 'latitude': '-14.2846'}, {'id': 'ATG', 'iso2Code': 'AG', 'name': 'Antigua and Barbuda', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': "Saint John's", 'longitude': '-61.8456', 'latitude': '17.1175'}, {'id': 'AUS', 'iso2Code': 'AU', 'name': 'Australia', 'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Canberra', 'longitude': '149.129', 'latitude': '-35.282'}, {'id': 'AUT', 'iso2Code': 'AT', 'name': 'Austria', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Vienna', 'longitude': '16.3798', 'latitude': '48.2201'}, {'id': 'AZE', 'iso2Code': 'AZ', 'name': 'Azerbaijan', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Baku', 'longitude': '49.8932', 'latitude': '40.3834'}, {'id': 'BDI', 'iso2Code': 'BI', 'name': 'Burundi', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Bujumbura', 'longitude': '29.3639', 'latitude': '-3.3784'}, {'id': 'BEA', 'iso2Code': 'B4', 'name': 'East Asia & Pacific (IBRD-only countries)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'BEC', 'iso2Code': 'B7', 'name': 'Europe & Central Asia (IBRD-only countries)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'BEL', 'iso2Code': 'BE', 'name': 'Belgium', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Brussels', 'longitude': '4.36761', 'latitude': '50.8371'}, {'id': 'BEN', 'iso2Code': 'BJ', 'name': 'Benin', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Porto-Novo', 'longitude': '2.6323', 'latitude': '6.4779'}, {'id': 'BFA', 'iso2Code': 'BF', 'name': 'Burkina Faso', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Ouagadougou', 'longitude': '-1.53395', 'latitude': '12.3605'}, {'id': 'BGD', 'iso2Code': 'BD', 'name': 'Bangladesh', 'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Dhaka', 'longitude': '90.4113', 'latitude': '23.7055'}, {'id': 'BGR', 'iso2Code': 'BG', 'name': 'Bulgaria', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Sofia', 'longitude': '23.3238', 'latitude': '42.7105'}, {'id': 'BHI', 'iso2Code': 'B1', 'name': 'IBRD countries classified as high income', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'BHR', 'iso2Code': 'BH', 'name': 'Bahrain', 'region': {'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Middle East, North Africa, Afghanistan & Pakistan'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Manama', 'longitude': '50.5354', 'latitude': '26.1921'}, {'id': 'BHS', 'iso2Code': 'BS', 'name': 'Bahamas, The', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Nassau', 'longitude': '-77.339', 'latitude': '25.0661'}, {'id': 'BIH', 'iso2Code': 'BA', 'name': 'Bosnia and Herzegovina', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Sarajevo', 'longitude': '18.4214', 'latitude': '43.8607'}, {'id': 'BLA', 'iso2Code': 'B2', 'name': 'Latin America & the Caribbean (IBRD-only countries)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'BLR', 'iso2Code': 'BY', 'name': 'Belarus', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': 'ECA', 'iso2code': '7E', 'value': 'Europe & Central Asia (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Minsk', 'longitude': '27.5766', 'latitude': '53.9678'}, {'id': 'BLZ', 'iso2Code': 'BZ', 'name': 'Belize', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': 'LAC', 'iso2code': 'XJ', 'value': 'Latin America & Caribbean (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}, 'capitalCity': 'Belmopan', 'longitude': '-88.7713', 'latitude': '17.2534'}, {'id': 'BMN', 'iso2Code': 'B3', 'name': 'Middle East, North Africa, Afghanistan & Pakistan (IBRD only)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'BMU', 'iso2Code': 'BM', 'name': 'Bermuda', 'region': {'id': 'NAC', 'iso2code': 'XU', 'value': 'North America'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Hamilton', 'longitude': '-64.706', 'latitude': '32.3293'}, {'id': 'BOL', 'iso2Code': 'BO', 'name': 'Bolivia', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': 'LAC', 'iso2code': 'XJ', 'value': 'Latin America & Caribbean (excluding high income)'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'La Paz', 'longitude': '-66.1936', 'latitude': '-13.9908'}, {'id': 'BRA', 'iso2Code': 'BR', 'name': 'Brazil', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': 'LAC', 'iso2code': 'XJ', 'value': 'Latin America & Caribbean (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Brasilia', 'longitude': '-47.9292', 'latitude': '-15.7801'}, {'id': 'BRB', 'iso2Code': 'BB', 'name': 'Barbados', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Bridgetown', 'longitude': '-59.6105', 'latitude': '13.0935'}, {'id': 'BRN', 'iso2Code': 'BN', 'name': 'Brunei Darussalam', 'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Bandar Seri Begawan', 'longitude': '114.946', 'latitude': '4.94199'}, {'id': 'BSS', 'iso2Code': 'B6', 'name': 'Sub-Saharan Africa (IBRD-only countries)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'BTN', 'iso2Code': 'BT', 'name': 'Bhutan', 'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}, 'incomeLevel': {'id': 'LMC', 'iso2code': 'XN', 'value': 'Lower middle income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Thimphu', 'longitude': '89.6177', 'latitude': '27.5768'}, {'id': 'BWA', 'iso2Code': 'BW', 'name': 'Botswana', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'UMC', 'iso2code': 'XT', 'value': 'Upper middle income'}, 'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}, 'capitalCity': 'Gaborone', 'longitude': '25.9201', 'latitude': '-24.6544'}, {'id': 'CAA', 'iso2Code': 'C9', 'name': 'Sub-Saharan Africa (IFC classification)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'CAF', 'iso2Code': 'CF', 'name': 'Central African Republic', 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}, 'adminregion': {'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-Saharan Africa (excluding high income)'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Bangui', 'longitude': '21.6407', 'latitude': '5.63056'}, {'id': 'CAN', 'iso2Code': 'CA', 'name': 'Canada', 'region': {'id': 'NAC', 'iso2code': 'XU', 'value': 'North America'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Ottawa', 'longitude': '-75.6919', 'latitude': '45.4215'}, {'id': 'CEA', 'iso2Code': 'C4', 'name': 'East Asia and the Pacific (IFC classification)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'CEB', 'iso2Code': 'B8', 'name': 'Central Europe and the Baltics', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'CEU', 'iso2Code': 'C5', 'name': 'Europe and Central Asia (IFC classification)', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'CHE', 'iso2Code': 'CH', 'name': 'Switzerland', 'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}, 'adminregion': {'id': '', 

In [61]:
data[0]

{'page': 1, 'pages': 1, 'per_page': '300', 'total': 296}

In [62]:
# meta data
#actual data
print(len(data))

2

In [63]:
countries = data[1]
countries_df = pd.DataFrame(countries)

In [64]:
countries_df

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
292,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
293,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
294,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [65]:
countries_df['region'] = countries_df['region'].apply(lambda x : x["value"])

In [66]:
countries_df

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
292,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
293,ZAF,ZA,South Africa,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
294,ZMB,ZM,Zambia,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [67]:
countries_df['incomeLevel'] = countries_df['incomeLevel'].apply(lambda x : x["value"])

In [68]:
countries_df['lendingType'] = countries_df['lendingType'].apply(lambda x : x["value"])

In [69]:
countries_df

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,"{'id': '', 'iso2code': '', 'value': ''}",High income,Not classified,Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}",Aggregates,Aggregates,,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...",Low income,IDA,Kabul,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}",Aggregates,Aggregates,,,
4,AFW,ZI,Africa Western and Central,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}",Aggregates,Aggregates,,,
...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,"{'id': '', 'iso2code': '', 'value': ''}",Aggregates,Aggregates,,,
292,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...",Low income,IDA,Sana'a,44.2075,15.352
293,ZAF,ZA,South Africa,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Upper middle income,IBRD,Pretoria,28.1871,-25.746
294,ZMB,ZM,Zambia,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Lower middle income,IDA,Lusaka,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...",Lower middle income,Blend,Harare,31.0672,-17.8312

In [70]:
countries_df.drop(columns= ['adminregion' , 'lendingType', 'adminregion'], inplace = True)

In [71]:
countries_df

,id,iso2Code,name,region,incomeLevel,capitalCity,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,High income,Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,Aggregates,,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,Kabul,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,Aggregates,,,
4,AFW,ZI,Africa Western and Central,Aggregates,Aggregates,,,
...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,Aggregates,,,
292,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan",Low income,Sana'a,44.2075,15.352
293,ZAF,ZA,South Africa,Sub-Saharan Africa,Upper middle income,Pretoria,28.1871,-25.746
294,ZMB,ZM,Zambia,Sub-Saharan Africa,Lower middle income,Lusaka,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Lower middle income,Harare,31.0672,-17.8312

In [72]:
countries_df.isnull().sum()

id             0
iso2Code       0
name           0
region         0
incomeLevel    0
capitalCity    0
longitude      0
latitude       0
dtype: int64

In [74]:
countries_df.shape

(296, 8)

In [75]:
countries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           296 non-null    object
 1   iso2Code     296 non-null    object
 2   name         296 non-null    object
 3   region       296 non-null    object
 4   incomeLevel  296 non-null    object
 5   capitalCity  296 non-null    object
 6   longitude    296 non-null    object
 7   latitude     296 non-null    object
dtypes: object(8)
memory usage: 18.6+ KB

In [76]:
countries_df.describe()

,id,iso2Code,name,region,incomeLevel,capitalCity,longitude,latitude
count,296,296,296,296,296,296,296,296
unique,296,296,296,8,6,212,212,212
top,ABW,AW,Aruba,Aggregates,High income,,,
freq,1,1,1,79,86,85,85,85

In [78]:
countries_df.drop('capitalCity', axis = 1, inplace = True)

In [79]:
countries_df

,id,iso2Code,name,region,incomeLevel,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,High income,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,Aggregates,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,Aggregates,,
4,AFW,ZI,Africa Western and Central,Aggregates,Aggregates,,
...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,Aggregates,,
292,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan",Low income,44.2075,15.352
293,ZAF,ZA,South Africa,Sub-Saharan Africa,Upper middle income,28.1871,-25.746
294,ZMB,ZM,Zambia,Sub-Saharan Africa,Lower middle income,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312

In [80]:
countries_df['region'].unique()

array(['Latin America & Caribbean ', 'Aggregates',
       'Middle East, North Africa, Afghanistan & Pakistan',
       'Sub-Saharan Africa ', 'Europe & Central Asia',
       'East Asia & Pacific', 'South Asia', 'North America'], dtype=object)

In [82]:
countries_df[countries_df['region'] == 'Aggregates']

,id,iso2Code,name,region,incomeLevel,longitude,latitude
1,AFE,ZH,Africa Eastern and Southern,Aggregates,Aggregates,,
3,AFR,A9,Africa,Aggregates,Aggregates,,
4,AFW,ZI,Africa Western and Central,Aggregates,Aggregates,,
8,ARB,1A,Arab World,Aggregates,Aggregates,,
18,BEA,B4,East Asia & Pacific (IBRD-only countries),Aggregates,Aggregates,,
...,...,...,...,...,...,...,...
269,TSA,T5,South Asia (IDA & IBRD),Aggregates,Aggregates,,
270,TSS,T6,Sub-Saharan Africa (IDA & IBRD countries),Aggregates,Aggregates,,
278,UMC,XT,Upper middle income,Aggregates,Aggregates,,
288,WLD,1W,World,Aggregates,Aggregates,,
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,Aggregates,,

## Indicators

In [83]:
base_url = "https://api.worldbank.org/v2/indicators?format=json"
response = requests.get(base_url)

In [84]:
response.status_code

200

In [85]:
indicator_data = response.json()

In [86]:
indicator_data[0]

{'page': 1, 'pages': 591, 'per_page': '50', 'total': 29512}

In [87]:
all_dfs = []

for i in range(1, 526):

    url = f"https://api.worldbank.org/v2/indicators?format=json&per_page=500&page={i}"

    response = requests.get(url)

    if response.status_code == 200:

        data = response.json()

        if len(data) < 2:
            print(f"No data at page {i}")
            continue

        indicators = data[1]

        df = pd.DataFrame([
            {
                "id": item["id"],
                "name": item["name"]
            }
            for item in indicators
        ])

        all_dfs.append(df)

        print(f"Page {i}: {len(df)} indicators collected")

    else:
        print(f"Failed to fetch page {i}, status_code={response.status_code}")

Page 1: 500 indicators collected
Page 2: 500 indicators collected
Page 3: 500 indicators collected
Page 4: 500 indicators collected
Page 5: 500 indicators collected
Page 6: 500 indicators collected
Page 7: 500 indicators collected
Page 8: 500 indicators collected
Page 9: 500 indicators collected
Page 10: 500 indicators collected
Page 11: 500 indicators collected
Page 12: 500 indicators collected
Page 13: 500 indicators collected
Page 14: 500 indicators collected
Page 15: 500 indicators collected
Page 16: 500 indicators collected
Page 17: 500 indicators collected
Page 18: 500 indicators collected
Page 19: 500 indicators collected
Page 20: 500 indicators collected
Page 21: 500 indicators collected
Page 22: 500 indicators collected
Page 23: 500 indicators collected
Page 24: 500 indicators collected
Page 25: 500 indicators collected
Page 26: 500 indicators collected
Page 27: 500 indicators collected
Page 28: 500 indicators collected
Page 29: 500 indicators collected
Page 30: 500 indicators collected
Page 31: 500 indicators collected
Page 32: 500 indicators collected
Page 33: 500 indicators collected
Page 34: 500 indicators collected
Page 35: 500 indicators collected
Page 36: 500 indicators collected
Page 37: 500 indicators collected
Page 38: 500 indicators collected
Page 39: 500 indicators collected
Page 40: 500 indicators collected
Page 41: 500 indicators collected
Page 42: 500 indicators collected
Page 43: 500 indicators collected
Page 44: 500 indicators collected
Page 45: 500 indicators collected
Page 46: 500 indicators collected
Page 47: 500 indicators collected
Page 48: 500 indicators collected
Page 49: 500 indicators collected
Page 50: 500 indicators collected
Page 51: 500 indicators collected
Page 52: 500 indicators collected
Page 53: 500 indicators collected
Page 54: 500 indicators collected
Page 55: 500 indicators collected
Page 56: 500 indicators collected
Page 57: 500 indicators collected
Page 58: 500 indicators collected
Page 59: 500 indicators collected
Page 60: 12 indicators collected
Page 61: 0 indicators collected
Page 62: 0 indicators collected
Page 63: 0 indicators collected
Page 64: 0 indicators collected
Page 65: 0 indicators collected
Page 66: 0 indicators collected
Page 67: 0 indicators collected
Page 68: 0 indicators collected
Page 69: 0 indicators collected
Page 70: 0 indicators collected
Page 71: 0 indicators collected
Page 72: 0 indicators collected
Page 73: 0 indicators collected
Page 74: 0 indicators collected
Page 75: 0 indicators collected
Page 76: 0 indicators collected
Page 77: 0 indicators collected
Page 78: 0 indicators collected
Page 79: 0 indicators collected
Page 80: 0 indicators collected
Page 81: 0 indicators collected
Page 82: 0 indicators collected
Page 83: 0 indicators collected
Page 84: 0 indicators collected
Page 85: 0 indicators collected
Page 86: 0 indicators collected
Page 87: 0 indicators collected
Page 88: 0 indicators collected
Page 89: 0 indicators collected
Page 90: 0 indicators collected
Page 91: 0 indicators collected
Page 92: 0 indicators collected
Page 93: 0 indicators collected
Page 94: 0 indicators collected
Page 95: 0 indicators collected
Page 96: 0 indicators collected
Page 97: 0 indicators collected
Page 98: 0 indicators collected
Page 99: 0 indicators collected
Page 100: 0 indicators collected
Page 101: 0 indicators collected
Page 102: 0 indicators collected
Page 103: 0 indicators collected
Page 104: 0 indicators collected
Page 105: 0 indicators collected
Page 106: 0 indicators collected
Page 107: 0 indicators collected
Page 108: 0 indicators collected
Page 109: 0 indicators collected
Page 110: 0 indicators collected
Page 111: 0 indicators collected
Page 112: 0 indicators collected
Page 113: 0 indicators collected
Page 114: 0 indicators collected
Page 115: 0 indicators collected
Page 116: 0 indicators collected
Page 117: 0 indicators collected
Page 118: 0 indicators collected
Page 119: 0 indicators collected
Page 120: 0 indicators collected
Page 121: 0 indicators collected
Page 122: 0 indicators collected
Page 123: 0 indicators collected
Page 124: 0 indicators collected
Page 125: 0 indicators collected
Page 126: 0 indicators collected
Page 127: 0 indicators collected
Page 128: 0 indicators collected
Page 129: 0 indicators collected
Page 130: 0 indicators collected
Page 131: 0 indicators collected
Page 132: 0 indicators collected
Page 133: 0 indicators collected
Page 134: 0 indicators collected
Page 135: 0 indicators collected
Page 136: 0 indicators collected
Page 137: 0 indicators collected
Page 138: 0 indicators collected
Page 139: 0 indicators collected
Page 140: 0 indicators collected
Page 141: 0 indicators collected
Page 142: 0 indicators collected
Page 143: 0 indicators collected
Page 144: 0 indicators collected
Page 145: 0 indicators collected
Page 146: 0 indicators collected
Page 147: 0 indicators collected
Page 148: 0 indicators collected
Page 149: 0 indicators collected
Page 150: 0 indicators collected
Page 151: 0 indicators collected
Page 152: 0 indicators collected
Page 153: 0 indicators collected
Page 154: 0 indicators collected
Page 155: 0 indicators collected
Page 156: 0 indicators collected
Page 157: 0 indicators collected
Page 158: 0 indicators collected
Page 159: 0 indicators collected
Page 160: 0 indicators collected
Page 161: 0 indicators collected
Page 162: 0 indicators collected
Page 163: 0 indicators collected
Page 164: 0 indicators collected
Page 165: 0 indicators collected
Page 166: 0 indicators collected
Page 167: 0 indicators collected
Page 168: 0 indicators collected
Page 169: 0 indicators collected
Page 170: 0 indicators collected
Page 171: 0 indicators collected
Page 172: 0 indicators collected
Page 173: 0 indicators collected
Page 174: 0 indicators collected
Page 175: 0 indicators collected
Page 176: 0 indicators collected
Page 177: 0 indicators collected
Page 178: 0 indicators collected
Page 179: 0 indicators collected
Page 180: 0 indicators collected
Page 181: 0 indicators collected
Page 182: 0 indicators collected
Page 183: 0 indicators collected
Page 184: 0 indicators collected
Page 185: 0 indicators collected
Page 186: 0 indicators collected
Page 187: 0 indicators collected
Page 188: 0 indicators collected
Page 189: 0 indicators collected
Page 190: 0 indicators collected
Page 191: 0 indicators collected
Page 192: 0 indicators collected
Page 193: 0 indicators collected
Page 194: 0 indicators collected
Page 195: 0 indicators collected
Page 196: 0 indicators collected
Page 197: 0 indicators collected
Page 198: 0 indicators collected
Page 199: 0 indicators collected
Page 200: 0 indicators collected
Page 201: 0 indicators collected
Page 202: 0 indicators collected
Page 203: 0 indicators collected
Page 204: 0 indicators collected
Page 205: 0 indicators collected
Page 206: 0 indicators collected
Page 207: 0 indicators collected
Page 208: 0 indicators collected
Page 209: 0 indicators collected
Page 210: 0 indicators collected
Page 211: 0 indicators collected
Page 212: 0 indicators collected
Page 213: 0 indicators collected
Page 214: 0 indicators collected
Page 215: 0 indicators collected
Page 216: 0 indicators collected
Page 217: 0 indicators collected
Page 218: 0 indicators collected
Page 219: 0 indicators collected
Page 220: 0 indicators collected
Page 221: 0 indicators collected
Page 222: 0 indicators collected
Page 223: 0 indicators collected
Page 224: 0 indicators collected
Page 225: 0 indicators collected
Page 226: 0 indicators collected
Page 227: 0 indicators collected
Page 228: 0 indicators collected
Page 229: 0 indicators collected
Page 230: 0 indicators collected
Page 231: 0 indicators collected
Page 232: 0 indicators collected
Page 233: 0 indicators collected
Page 234: 0 indicators collected
Page 235: 0 indicators collected
Page 236: 0 indicators collected
Page 237: 0 indicators collected
Page 238: 0 indicators collected
Page 239: 0 indicators collected
Page 240: 0 indicators collected
Page 241: 0 indicators collected
Page 242: 0 indicators collected
Page 243: 0 indicators collected
Page 244: 0 indicators collected
Page 245: 0 indicators collected
Page 246: 0 indicators collected
Page 247: 0 indicators collected
Page 248: 0 indicators collected
Page 249: 0 indicators collected
Page 250: 0 indicators collected
Page 251: 0 indicators collected
Page 252: 0 indicators collected
Page 253: 0 indicators collected
Page 254: 0 indicators collected
Page 255: 0 indicators collected
Page 256: 0 indicators collected
Page 257: 0 indicators collected
Page 258: 0 indicators collected
Page 259: 0 indicators collected
Page 260: 0 indicators collected
Page 261: 0 indicators collected
Page 262: 0 indicators collected
Page 263: 0 indicators collected
Page 264: 0 indicators collected
Page 265: 0 indicators collected
Page 266: 0 indicators collected
Page 267: 0 indicators collected
Page 268: 0 indicators collected
Page 269: 0 indicators collected
Page 270: 0 indicators collected
Page 271: 0 indicators collected
Page 272: 0 indicators collected
Page 273: 0 indicators collected
Page 274: 0 indicators collected
Page 275: 0 indicators collected
Page 276: 0 indicators collected
Page 277: 0 indicators collected
Page 278: 0 indicators collected
Page 279: 0 indicators collected
Page 280: 0 indicators collected
Page 281: 0 indicators collected
Page 282: 0 indicators collected
Page 283: 0 indicators collected
Page 284: 0 indicators collected
Page 285: 0 indicators collected
Page 286: 0 indicators collected
Page 287: 0 indicators collected
Page 288: 0 indicators collected
Page 289: 0 indicators collected
Page 290: 0 indicators collected
Page 291: 0 indicators collected
Page 292: 0 indicators collected
Page 293: 0 indicators collected
Page 294: 0 indicators collected
Page 295: 0 indicators collected
Page 296: 0 indicators collected
Page 297: 0 indicators collected
Page 298: 0 indicators collected
Page 299: 0 indicators collected
Page 300: 0 indicators collected
Page 301: 0 indicators collected
Page 302: 0 indicators collected
Page 303: 0 indicators collected
Page 304: 0 indicators collected
Page 305: 0 indicators collected
Page 306: 0 indicators collected
Page 307: 0 indicators collected
Page 308: 0 indicators collected
Page 309: 0 indicators collected
Page 310: 0 indicators collected
Page 311: 0 indicators collected
Page 312: 0 indicators collected
Page 313: 0 indicators collected
Page 314: 0 indicators collected
Page 315: 0 indicators collected
Page 316: 0 indicators collected
Page 317: 0 indicators collected
Page 318: 0 indicators collected
Page 319: 0 indicators collected
Page 320: 0 indicators collected
Page 321: 0 indicators collected
Page 322: 0 indicators collected
Page 323: 0 indicators collected
Page 324: 0 indicators collected
Page 325: 0 indicators collected
Page 326: 0 indicators collected
Page 327: 0 indicators collected
Page 328: 0 indicators collected
Page 329: 0 indicators collected
Page 330: 0 indicators collected
Page 331: 0 indicators collected
Page 332: 0 indicators collected
Page 333: 0 indicators collected
Page 334: 0 indicators collected
Page 335: 0 indicators collected
Page 336: 0 indicators collected
Page 337: 0 indicators collected
Page 338: 0 indicators collected
Page 339: 0 indicators collected
Page 340: 0 indicators collected
Page 341: 0 indicators collected
Page 342: 0 indicators collected
Page 343: 0 indicators collected
Page 344: 0 indicators collected
Page 345: 0 indicators collected
Page 346: 0 indicators collected
Page 347: 0 indicators collected
Page 348: 0 indicators collected
Page 349: 0 indicators collected
Page 350: 0 indicators collected
Page 351: 0 indicators collected
Page 352: 0 indicators collected
Page 353: 0 indicators collected
Page 354: 0 indicators collected
Page 355: 0 indicators collected
Page 356: 0 indicators collected
Page 357: 0 indicators collected
Page 358: 0 indicators collected
Page 359: 0 indicators collected
Page 360: 0 indicators collected
Page 361: 0 indicators collected
Page 362: 0 indicators collected
Page 363: 0 indicators collected
Page 364: 0 indicators collected
Page 365: 0 indicators collected
Page 366: 0 indicators collected
Page 367: 0 indicators collected
Page 368: 0 indicators collected
Page 369: 0 indicators collected
Page 370: 0 indicators collected
Page 371: 0 indicators collected
Page 372: 0 indicators collected
Page 373: 0 indicators collected
Page 374: 0 indicators collected
Page 375: 0 indicators collected
Page 376: 0 indicators collected
Page 377: 0 indicators collected
Page 378: 0 indicators collected
Page 379: 0 indicators collected
Page 380: 0 indicators collected
Page 381: 0 indicators collected
Page 382: 0 indicators collected
Page 383: 0 indicators collected
Page 384: 0 indicators collected
Page 385: 0 indicators collected
Page 386: 0 indicators collected
Page 387: 0 indicators collected
Page 388: 0 indicators collected
Page 389: 0 indicators collected
Page 390: 0 indicators collected
Page 391: 0 indicators collected
Page 392: 0 indicators collected
Page 393: 0 indicators collected
Page 394: 0 indicators collected
Page 395: 0 indicators collected
Page 396: 0 indicators collected
Page 397: 0 indicators collected
Page 398: 0 indicators collected
Page 399: 0 indicators collected
Page 400: 0 indicators collected
Page 401: 0 indicators collected
Page 402: 0 indicators collected
Page 403: 0 indicators collected
Page 404: 0 indicators collected
Page 405: 0 indicators collected
Page 406: 0 indicators collected
Page 407: 0 indicators collected
Page 408: 0 indicators collected
Page 409: 0 indicators collected
Page 410: 0 indicators collected
Page 411: 0 indicators collected
Page 412: 0 indicators collected
Page 413: 0 indicators collected
Page 414: 0 indicators collected
Page 415: 0 indicators collected
Page 416: 0 indicators collected
Page 417: 0 indicators collected
Page 418: 0 indicators collected
Page 419: 0 indicators collected
Page 420: 0 indicators collected
Page 421: 0 indicators collected
Page 422: 0 indicators collected
Page 423: 0 indicators collected
Page 424: 0 indicators collected
Page 425: 0 indicators collected
Page 426: 0 indicators collected
Page 427: 0 indicators collected
Page 428: 0 indicators collected
Page 429: 0 indicators collected
Page 430: 0 indicators collected
Page 431: 0 indicators collected
Page 432: 0 indicators collected
Page 433: 0 indicators collected
Page 434: 0 indicators collected
Page 435: 0 indicators collected
Page 436: 0 indicators collected
Page 437: 0 indicators collected
Page 438: 0 indicators collected
Page 439: 0 indicators collected
Page 440: 0 indicators collected
Page 441: 0 indicators collected
Page 442: 0 indicators collected
Page 443: 0 indicators collected
Page 444: 0 indicators collected
Page 445: 0 indicators collected
Page 446: 0 indicators collected
Page 447: 0 indicators collected
Page 448: 0 indicators collected
Page 449: 0 indicators collected
Page 450: 0 indicators collected
Page 451: 0 indicators collected
Page 452: 0 indicators collected
Page 453: 0 indicators collected
Page 454: 0 indicators collected
Page 455: 0 indicators collected
Page 456: 0 indicators collected
Page 457: 0 indicators collected
Page 458: 0 indicators collected
Page 459: 0 indicators collected
Page 460: 0 indicators collected
Page 461: 0 indicators collected
Page 462: 0 indicators collected
Page 463: 0 indicators collected
Page 464: 0 indicators collected
Page 465: 0 indicators collected
Page 466: 0 indicators collected
Page 467: 0 indicators collected
Page 468: 0 indicators collected
Page 469: 0 indicators collected
Page 470: 0 indicators collected
Page 471: 0 indicators collected
Page 472: 0 indicators collected
Page 473: 0 indicators collected
Page 474: 0 indicators collected
Page 475: 0 indicators collected
Page 476: 0 indicators collected
Page 477: 0 indicators collected
Page 478: 0 indicators collected
Page 479: 0 indicators collected
Page 480: 0 indicators collected
Page 481: 0 indicators collected
Page 482: 0 indicators collected
Page 483: 0 indicators collected
Page 484: 0 indicators collected
Page 485: 0 indicators collected
Page 486: 0 indicators collected
Page 487: 0 indicators collected
Page 488: 0 indicators collected
Page 489: 0 indicators collected
Page 490: 0 indicators collected
Page 491: 0 indicators collected
Page 492: 0 indicators collected
Page 493: 0 indicators collected
Page 494: 0 indicators collected
Page 495: 0 indicators collected
Page 496: 0 indicators collected
Page 497: 0 indicators collected
Page 498: 0 indicators collected
Page 499: 0 indicators collected
Page 500: 0 indicators collected
Page 501: 0 indicators collected
Page 502: 0 indicators collected
Page 503: 0 indicators collected
Page 504: 0 indicators collected
Page 505: 0 indicators collected
Page 506: 0 indicators collected
Page 507: 0 indicators collected
Page 508: 0 indicators collected
Page 509: 0 indicators collected
Page 510: 0 indicators collected
Page 511: 0 indicators collected
Page 512: 0 indicators collected
Page 513: 0 indicators collected
Page 514: 0 indicators collected
Page 515: 0 indicators collected
Page 516: 0 indicators collected
Page 517: 0 indicators collected
Page 518: 0 indicators collected
Page 519: 0 indicators collected
Page 520: 0 indicators collected
Page 521: 0 indicators collected
Page 522: 0 indicators collected
Page 523: 0 indicators collected
Page 524: 0 indicators collected
Page 525: 0 indicators collected

In [88]:
final_df = pd.concat(all_dfs , ignore_index = True)

In [89]:
final_df.to_csv("final_df.csv")

In [91]:
indicators_groups = {

    "population": [
        "SP.POP.TOTL",        # Total Population
        "SP.DYN.LE00.IN",     # Life Expectancy at Birth
        "SP.DYN.CBRT.IN",     # Birth Rate
        "SP.DYN.CDRT.IN",     # Death Rate
        "SP.URB.TOTL.IN.ZS"   # Urban Population (%)
    ],

    "economy": [
        "NY.GDP.MKTP.CD",      # GDP (Current US$)
        "NY.GDP.PCAP.CD",      # GDP Per Capita
        "NY.GDP.MKTP.KD.ZG",   # GDP Growth (%)
        "FP.CPI.TOTL.ZG",      # Inflation (%)
        "SL.UEM.TOTL.ZS"       # Unemployment (%)
    ],

    "education": [
        "SE.ADT.LITR.ZS",      # Adult Literacy Rate
        "SE.PRM.ENRR",         # Primary School Enrollment
        "SE.SEC.ENRR",         # Secondary School Enrollment
        "SE.TER.ENRR",         # Tertiary School Enrollment
        "SE.XPD.TOTL.GD.ZS"    # Education Expenditure (% GDP)
    ],

    "health": [
        "SH.XPD.CHEX.GD.ZS",   # Health Expenditure (% GDP)
        "SH.DYN.MORT",         # Under-5 Mortality Rate
        "SH.STA.MMRT",         # Maternal Mortality Ratio
        "SH.MED.PHYS.ZS",      # Physicians per 1000 People
        "SH.IMM.MEAS"          # Measles Immunization (%)
    ],

    "environment": [
        "EN.ATM.CO2E.PC",      # CO2 Emissions per Capita
        "AG.LND.FRST.ZS",      # Forest Area (%)
        "EG.USE.PCAP.KG.OE",   # Energy Use per Capita
        "EG.ELC.ACCS.ZS",      # Access to Electricity (%)
        "ER.H2O.INTR.PC"       # Renewable Water Resources
    ],

    "technology": [
        "IT.NET.USER.ZS",      # Internet Users (%)
        "IT.CEL.SETS.P2",      # Mobile Cellular Subscriptions
        "IT.NET.BBND.P2",      # Fixed Broadband Subscriptions
        "IT.NET.SECR.P6",      # Secure Internet Servers
        "IP.JRN.ARTC.SC"       # Scientific & Technical Journal Articles
    ]

}

In [92]:
import time
base_url = "https://api.worldbank.org/v2/country/all/indicator/{}?format=json&per_page=1000&page={}"
category_dataframes = {}

for category, indicators in indicators_groups.items():

    print(f"\nFetching category: {category}")

    all_dfs_for_category = []

    for indicator_code in indicators:

        print(f"Fetching indicator: {indicator_code}")

        page = 1

        while True:

            url = base_url.format(indicator_code, page)

            response = requests.get(url)

            if response.status_code != 200:
                print(f"Failed to fetch page {page} for {indicator_code}")
                break

            data = response.json()

            if len(data) < 2:
                print(f"No data found for {indicator_code}")
                break

            total_pages = data[0]["pages"]

            records = data[1]

            if not records:
                break

            df = pd.json_normalize(records)

            # Rename nested columns
            df = df.rename(columns={
                "country.id": "country_code",
                "country.value": "country_name",
                "indicator.id": "indicator_code",
                "indicator.value": "indicator_name",
                "countryiso3code": "iso3_code",
                "date": "year",
                "value": "indicator_value"
            })

            # Keep useful columns only
            useful_cols = [
                "country_code",
                "country_name",
                "iso3_code",
                "indicator_code",
                "indicator_name",
                "year",
                "indicator_value"
            ]

            available_cols = [
                col for col in useful_cols
                if col in df.columns
            ]

            df = df[available_cols]

            # Convert year to numeric
            df["year"] = pd.to_numeric(
                df["year"],
                errors="coerce"
            )

            # Keep post-2015 data
            df = df[df["year"] >= 2015]

            all_dfs_for_category.append(df)

            print(
                f"{indicator_code} | Page {page}/{total_pages} | Rows: {len(df)}"
            )

            if page >= total_pages:
                break

            page += 1

            time.sleep(0.3)

    # Combine all indicators of category

    if all_dfs_for_category:

        combined_df = pd.concat(
            all_dfs_for_category,
            ignore_index=True
        )

        category_dataframes[category] = combined_df

        print(
            f"{category} -> {len(combined_df)} total rows collected"
        )

    else:

        print(
            f"No data collected for category: {category}"
        )

Fetching category: population
Fetching indicator: SP.POP.TOTL
SP.POP.TOTL | Page 1/18 | Rows: 175
SP.POP.TOTL | Page 2/18 | Rows: 166
SP.POP.TOTL | Page 3/18 | Rows: 165
SP.POP.TOTL | Page 4/18 | Rows: 165
SP.POP.TOTL | Page 5/18 | Rows: 165
SP.POP.TOTL | Page 6/18 | Rows: 165
SP.POP.TOTL | Page 7/18 | Rows: 169
SP.POP.TOTL | Page 8/18 | Rows: 172
SP.POP.TOTL | Page 9/18 | Rows: 165
SP.POP.TOTL | Page 10/18 | Rows: 165
SP.POP.TOTL | Page 11/18 | Rows: 165
SP.POP.TOTL | Page 12/18 | Rows: 165
SP.POP.TOTL | Page 13/18 | Rows: 165
SP.POP.TOTL | Page 14/18 | Rows: 173
SP.POP.TOTL | Page 15/18 | Rows: 168
SP.POP.TOTL | Page 16/18 | Rows: 165
SP.POP.TOTL | Page 17/18 | Rows: 165
SP.POP.TOTL | Page 18/18 | Rows: 88
Fetching indicator: SP.DYN.LE00.IN
SP.DYN.LE00.IN | Page 1/18 | Rows: 175
SP.DYN.LE00.IN | Page 2/18 | Rows: 166
SP.DYN.LE00.IN | Page 3/18 | Rows: 165
SP.DYN.LE00.IN | Page 4/18 | Rows: 165
SP.DYN.LE00.IN | Page 5/18 | Rows: 165
SP.DYN.LE00.IN | Page 6/18 | Rows: 165
SP.DYN.LE00.IN | Page 7/18 | Rows: 169
SP.DYN.LE00.IN | Page 8/18 | Rows: 172
SP.DYN.LE00.IN | Page 9/18 | Rows: 165
SP.DYN.LE00.IN | Page 10/18 | Rows: 165
SP.DYN.LE00.IN | Page 11/18 | Rows: 165
SP.DYN.LE00.IN | Page 12/18 | Rows: 165
SP.DYN.LE00.IN | Page 13/18 | Rows: 165
SP.DYN.LE00.IN | Page 14/18 | Rows: 173
SP.DYN.LE00.IN | Page 15/18 | Rows: 168
SP.DYN.LE00.IN | Page 16/18 | Rows: 165
SP.DYN.LE00.IN | Page 17/18 | Rows: 165
SP.DYN.LE00.IN | Page 18/18 | Rows: 88
Fetching indicator: SP.DYN.CBRT.IN
SP.DYN.CBRT.IN | Page 1/18 | Rows: 175
SP.DYN.CBRT.IN | Page 2/18 | Rows: 166
SP.DYN.CBRT.IN | Page 3/18 | Rows: 165
SP.DYN.CBRT.IN | Page 4/18 | Rows: 165
SP.DYN.CBRT.IN | Page 5/18 | Rows: 165
SP.DYN.CBRT.IN | Page 6/18 | Rows: 165
SP.DYN.CBRT.IN | Page 7/18 | Rows: 169
SP.DYN.CBRT.IN | Page 8/18 | Rows: 172
SP.DYN.CBRT.IN | Page 9/18 | Rows: 165
SP.DYN.CBRT.IN | Page 10/18 | Rows: 165
SP.DYN.CBRT.IN | Page 11/18 | Rows: 165
SP.DYN.CBRT.IN | Page 12/18 | Rows: 165
SP.DYN.CBRT.IN | Page 13/18 | Rows: 165
SP.DYN.CBRT.IN | Page 14/18 | Rows: 173
SP.DYN.CBRT.IN | Page 15/18 | Rows: 168
SP.DYN.CBRT.IN | Page 16/18 | Rows: 165
SP.DYN.CBRT.IN | Page 17/18 | Rows: 165
SP.DYN.CBRT.IN | Page 18/18 | Rows: 88
Fetching indicator: SP.DYN.CDRT.IN
SP.DYN.CDRT.IN | Page 1/18 | Rows: 175
SP.DYN.CDRT.IN | Page 2/18 | Rows: 166
SP.DYN.CDRT.IN | Page 3/18 | Rows: 165
SP.DYN.CDRT.IN | Page 4/18 | Rows: 165
SP.DYN.CDRT.IN | Page 5/18 | Rows: 165
SP.DYN.CDRT.IN | Page 6/18 | Rows: 165
SP.DYN.CDRT.IN | Page 7/18 | Rows: 169
SP.DYN.CDRT.IN | Page 8/18 | Rows: 172
SP.DYN.CDRT.IN | Page 9/18 | Rows: 165
SP.DYN.CDRT.IN | Page 10/18 | Rows: 165
SP.DYN.CDRT.IN | Page 11/18 | Rows: 165
SP.DYN.CDRT.IN | Page 12/18 | Rows: 165
SP.DYN.CDRT.IN | Page 13/18 | Rows: 165
SP.DYN.CDRT.IN | Page 14/18 | Rows: 173
SP.DYN.CDRT.IN | Page 15/18 | Rows: 168
SP.DYN.CDRT.IN | Page 16/18 | Rows: 165
SP.DYN.CDRT.IN | Page 17/18 | Rows: 165
SP.DYN.CDRT.IN | Page 18/18 | Rows: 88
Fetching indicator: SP.URB.TOTL.IN.ZS
SP.URB.TOTL.IN.ZS | Page 1/18 | Rows: 175
SP.URB.TOTL.IN.ZS | Page 2/18 | Rows: 166
SP.URB.TOTL.IN.ZS | Page 3/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 4/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 5/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 6/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 7/18 | Rows: 169
SP.URB.TOTL.IN.ZS | Page 8/18 | Rows: 172
SP.URB.TOTL.IN.ZS | Page 9/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 10/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 11/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 12/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 13/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 14/18 | Rows: 173
SP.URB.TOTL.IN.ZS | Page 15/18 | Rows: 168
SP.URB.TOTL.IN.ZS | Page 16/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 17/18 | Rows: 165
SP.URB.TOTL.IN.ZS | Page 18/18 | Rows: 88
population -> 14630 total rows collected

Fetching category: economy
Fetching indicator: NY.GDP.MKTP.CD
NY.GDP.MKTP.CD | Page 1/18 | Rows: 175
NY.GDP.MKTP.CD | Page 2/18 | Rows: 166
NY.GDP.MKTP.CD | Page 3/18 | Rows: 165
NY.GDP.MKTP.CD | Page 4/18 | Rows: 165
NY.GDP.MKTP.CD | Page 5/18 | Rows: 165
NY.GDP.MKTP.CD | Page 6/18 | Rows: 165
NY.GDP.MKTP.CD | Page 7/18 | Rows: 169
NY.GDP.MKTP.CD | Page 8/18 | Rows: 172
NY.GDP.MKTP.CD | Page 9/18 | Rows: 165
NY.GDP.MKTP.CD | Page 10/18 | Rows: 165
NY.GDP.MKTP.CD | Page 11/18 | Rows: 165
NY.GDP.MKTP.CD | Page 12/18 | Rows: 165
NY.GDP.MKTP.CD | Page 13/18 | Rows: 165
NY.GDP.MKTP.CD | Page 14/18 | Rows: 173
NY.GDP.MKTP.CD | Page 15/18 | Rows: 168
NY.GDP.MKTP.CD | Page 16/18 | Rows: 165
NY.GDP.MKTP.CD | Page 17/18 | Rows: 165
NY.GDP.MKTP.CD | Page 18/18 | Rows: 88
Fetching indicator: NY.GDP.PCAP.CD
NY.GDP.PCAP.CD | Page 1/18 | Rows: 175
NY.GDP.PCAP.CD | Page 2/18 | Rows: 166
NY.GDP.PCAP.CD | Page 3/18 | Rows: 165
NY.GDP.PCAP.CD | Page 4/18 | Rows: 165
NY.GDP.PCAP.CD | Page 5/18 | Rows: 165
NY.GDP.PCAP.CD | Page 6/18 | Rows: 165
NY.GDP.PCAP.CD | Page 7/18 | Rows: 169
NY.GDP.PCAP.CD | Page 8/18 | Rows: 172
NY.GDP.PCAP.CD | Page 9/18 | Rows: 165
NY.GDP.PCAP.CD | Page 10/18 | Rows: 165
NY.GDP.PCAP.CD | Page 11/18 | Rows: 165
NY.GDP.PCAP.CD | Page 12/18 | Rows: 165
NY.GDP.PCAP.CD | Page 13/18 | Rows: 165
NY.GDP.PCAP.CD | Page 14/18 | Rows: 173
NY.GDP.PCAP.CD | Page 15/18 | Rows: 168
NY.GDP.PCAP.CD | Page 16/18 | Rows: 165
NY.GDP.PCAP.CD | Page 17/18 | Rows: 165
NY.GDP.PCAP.CD | Page 18/18 | Rows: 88
Fetching indicator: NY.GDP.MKTP.KD.ZG
NY.GDP.MKTP.KD.ZG | Page 1/18 | Rows: 175
NY.GDP.MKTP.KD.ZG | Page 2/18 | Rows: 166
NY.GDP.MKTP.KD.ZG | Page 3/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 4/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 5/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 6/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 7/18 | Rows: 169
NY.GDP.MKTP.KD.ZG | Page 8/18 | Rows: 172
NY.GDP.MKTP.KD.ZG | Page 9/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 10/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 11/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 12/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 13/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 14/18 | Rows: 173
NY.GDP.MKTP.KD.ZG | Page 15/18 | Rows: 168
NY.GDP.MKTP.KD.ZG | Page 16/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 17/18 | Rows: 165
NY.GDP.MKTP.KD.ZG | Page 18/18 | Rows: 88
Fetching indicator: FP.CPI.TOTL.ZG
FP.CPI.TOTL.ZG | Page 1/18 | Rows: 175
FP.CPI.TOTL.ZG | Page 2/18 | Rows: 166
FP.CPI.TOTL.ZG | Page 3/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 4/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 5/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 6/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 7/18 | Rows: 169
FP.CPI.TOTL.ZG | Page 8/18 | Rows: 172
FP.CPI.TOTL.ZG | Page 9/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 10/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 11/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 12/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 13/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 14/18 | Rows: 173
FP.CPI.TOTL.ZG | Page 15/18 | Rows: 168
FP.CPI.TOTL.ZG | Page 16/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 17/18 | Rows: 165
FP.CPI.TOTL.ZG | Page 18/18 | Rows: 88
Fetching indicator: SL.UEM.TOTL.ZS
SL.UEM.TOTL.ZS | Page 1/18 | Rows: 175
SL.UEM.TOTL.ZS | Page 2/18 | Rows: 166
SL.UEM.TOTL.ZS | Page 3/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 4/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 5/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 6/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 7/18 | Rows: 169
SL.UEM.TOTL.ZS | Page 8/18 | Rows: 172
SL.UEM.TOTL.ZS | Page 9/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 10/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 11/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 12/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 13/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 14/18 | Rows: 173
SL.UEM.TOTL.ZS | Page 15/18 | Rows: 168
SL.UEM.TOTL.ZS | Page 16/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 17/18 | Rows: 165
SL.UEM.TOTL.ZS | Page 18/18 | Rows: 88
economy -> 14630 total rows collected

Fetching category: education
Fetching indicator: SE.ADT.LITR.ZS

C:\Users\utkar\AppData\Local\Temp\ipykernel_16880\2286875169.py:97: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat(

SE.ADT.LITR.ZS | Page 1/18 | Rows: 175
SE.ADT.LITR.ZS | Page 2/18 | Rows: 166
SE.ADT.LITR.ZS | Page 3/18 | Rows: 165
SE.ADT.LITR.ZS | Page 4/18 | Rows: 165
SE.ADT.LITR.ZS | Page 5/18 | Rows: 165
SE.ADT.LITR.ZS | Page 6/18 | Rows: 165
SE.ADT.LITR.ZS | Page 7/18 | Rows: 169
SE.ADT.LITR.ZS | Page 8/18 | Rows: 172
SE.ADT.LITR.ZS | Page 9/18 | Rows: 165
SE.ADT.LITR.ZS | Page 10/18 | Rows: 165
SE.ADT.LITR.ZS | Page 11/18 | Rows: 165
SE.ADT.LITR.ZS | Page 12/18 | Rows: 165
SE.ADT.LITR.ZS | Page 13/18 | Rows: 165
SE.ADT.LITR.ZS | Page 14/18 | Rows: 173
SE.ADT.LITR.ZS | Page 15/18 | Rows: 168
SE.ADT.LITR.ZS | Page 16/18 | Rows: 165
SE.ADT.LITR.ZS | Page 17/18 | Rows: 165
SE.ADT.LITR.ZS | Page 18/18 | Rows: 88
Fetching indicator: SE.PRM.ENRR
SE.PRM.ENRR | Page 1/18 | Rows: 175
SE.PRM.ENRR | Page 2/18 | Rows: 166
SE.PRM.ENRR | Page 3/18 | Rows: 165
SE.PRM.ENRR | Page 4/18 | Rows: 165
SE.PRM.ENRR | Page 5/18 | Rows: 165
SE.PRM.ENRR | Page 6/18 | Rows: 165
SE.PRM.ENRR | Page 7/18 | Rows: 169
SE.PRM.ENRR | Page 8/18 | Rows: 172
SE.PRM.ENRR | Page 9/18 | Rows: 165
SE.PRM.ENRR | Page 10/18 | Rows: 165
SE.PRM.ENRR | Page 11/18 | Rows: 165
SE.PRM.ENRR | Page 12/18 | Rows: 165
SE.PRM.ENRR | Page 13/18 | Rows: 165
SE.PRM.ENRR | Page 14/18 | Rows: 173
SE.PRM.ENRR | Page 15/18 | Rows: 168
SE.PRM.ENRR | Page 16/18 | Rows: 165
SE.PRM.ENRR | Page 17/18 | Rows: 165
SE.PRM.ENRR | Page 18/18 | Rows: 88
Fetching indicator: SE.SEC.ENRR
SE.SEC.ENRR | Page 1/18 | Rows: 175
SE.SEC.ENRR | Page 2/18 | Rows: 166
SE.SEC.ENRR | Page 3/18 | Rows: 165
SE.SEC.ENRR | Page 4/18 | Rows: 165
SE.SEC.ENRR | Page 5/18 | Rows: 165
SE.SEC.ENRR | Page 6/18 | Rows: 165
SE.SEC.ENRR | Page 7/18 | Rows: 169
SE.SEC.ENRR | Page 8/18 | Rows: 172
SE.SEC.ENRR | Page 9/18 | Rows: 165
SE.SEC.ENRR | Page 10/18 | Rows: 165
SE.SEC.ENRR | Page 11/18 | Rows: 165
SE.SEC.ENRR | Page 12/18 | Rows: 165
SE.SEC.ENRR | Page 13/18 | Rows: 165
SE.SEC.ENRR | Page 14/18 | Rows: 173
SE.SEC.ENRR | Page 15/18 | Rows: 168
SE.SEC.ENRR | Page 16/18 | Rows: 165
SE.SEC.ENRR | Page 17/18 | Rows: 165
SE.SEC.ENRR | Page 18/18 | Rows: 88
Fetching indicator: SE.TER.ENRR
SE.TER.ENRR | Page 1/18 | Rows: 175
SE.TER.ENRR | Page 2/18 | Rows: 166
SE.TER.ENRR | Page 3/18 | Rows: 165
SE.TER.ENRR | Page 4/18 | Rows: 165
SE.TER.ENRR | Page 5/18 | Rows: 165
SE.TER.ENRR | Page 6/18 | Rows: 165
SE.TER.ENRR | Page 7/18 | Rows: 169
SE.TER.ENRR | Page 8/18 | Rows: 172
SE.TER.ENRR | Page 9/18 | Rows: 165
SE.TER.ENRR | Page 10/18 | Rows: 165
SE.TER.ENRR | Page 11/18 | Rows: 165
SE.TER.ENRR | Page 12/18 | Rows: 165
SE.TER.ENRR | Page 13/18 | Rows: 165
SE.TER.ENRR | Page 14/18 | Rows: 173
SE.TER.ENRR | Page 15/18 | Rows: 168
SE.TER.ENRR | Page 16/18 | Rows: 165
SE.TER.ENRR | Page 17/18 | Rows: 165
SE.TER.ENRR | Page 18/18 | Rows: 88
Fetching indicator: SE.XPD.TOTL.GD.ZS
SE.XPD.TOTL.GD.ZS | Page 1/18 | Rows: 175
SE.XPD.TOTL.GD.ZS | Page 2/18 | Rows: 166
SE.XPD.TOTL.GD.ZS | Page 3/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 4/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 5/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 6/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 7/18 | Rows: 169
SE.XPD.TOTL.GD.ZS | Page 8/18 | Rows: 172
SE.XPD.TOTL.GD.ZS | Page 9/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 10/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 11/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 12/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 13/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 14/18 | Rows: 173
SE.XPD.TOTL.GD.ZS | Page 15/18 | Rows: 168
SE.XPD.TOTL.GD.ZS | Page 16/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 17/18 | Rows: 165
SE.XPD.TOTL.GD.ZS | Page 18/18 | Rows: 88
education -> 14630 total rows collected

Fetching category: health
Fetching indicator: SH.XPD.CHEX.GD.ZS
SH.XPD.CHEX.GD.ZS | Page 1/18 | Rows: 175
SH.XPD.CHEX.GD.ZS | Page 2/18 | Rows: 166
SH.XPD.CHEX.GD.ZS | Page 3/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 4/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 5/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 6/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 7/18 | Rows: 169
SH.XPD.CHEX.GD.ZS | Page 8/18 | Rows: 172
SH.XPD.CHEX.GD.ZS | Page 9/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 10/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 11/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 12/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 13/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 14/18 | Rows: 173
SH.XPD.CHEX.GD.ZS | Page 15/18 | Rows: 168
SH.XPD.CHEX.GD.ZS | Page 16/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 17/18 | Rows: 165
SH.XPD.CHEX.GD.ZS | Page 18/18 | Rows: 88
Fetching indicator: SH.DYN.MORT
SH.DYN.MORT | Page 1/18 | Rows: 175
SH.DYN.MORT | Page 2/18 | Rows: 166
SH.DYN.MORT | Page 3/18 | Rows: 165
SH.DYN.MORT | Page 4/18 | Rows: 165
SH.DYN.MORT | Page 5/18 | Rows: 165
SH.DYN.MORT | Page 6/18 | Rows: 165
SH.DYN.MORT | Page 7/18 | Rows: 169
SH.DYN.MORT | Page 8/18 | Rows: 172
SH.DYN.MORT | Page 9/18 | Rows: 165
SH.DYN.MORT | Page 10/18 | Rows: 165
SH.DYN.MORT | Page 11/18 | Rows: 165
SH.DYN.MORT | Page 12/18 | Rows: 165
SH.DYN.MORT | Page 13/18 | Rows: 165
SH.DYN.MORT | Page 14/18 | Rows: 173
SH.DYN.MORT | Page 15/18 | Rows: 168
SH.DYN.MORT | Page 16/18 | Rows: 165
SH.DYN.MORT | Page 17/18 | Rows: 165
SH.DYN.MORT | Page 18/18 | Rows: 88
Fetching indicator: SH.STA.MMRT
SH.STA.MMRT | Page 1/18 | Rows: 175
SH.STA.MMRT | Page 2/18 | Rows: 166
SH.STA.MMRT | Page 3/18 | Rows: 165
SH.STA.MMRT | Page 4/18 | Rows: 165
SH.STA.MMRT | Page 5/18 | Rows: 165
SH.STA.MMRT | Page 6/18 | Rows: 165
SH.STA.MMRT | Page 7/18 | Rows: 169
SH.STA.MMRT | Page 8/18 | Rows: 172
SH.STA.MMRT | Page 9/18 | Rows: 165
SH.STA.MMRT | Page 10/18 | Rows: 165
SH.STA.MMRT | Page 11/18 | Rows: 165
SH.STA.MMRT | Page 12/18 | Rows: 165
SH.STA.MMRT | Page 13/18 | Rows: 165
SH.STA.MMRT | Page 14/18 | Rows: 173
SH.STA.MMRT | Page 15/18 | Rows: 168
SH.STA.MMRT | Page 16/18 | Rows: 165
SH.STA.MMRT | Page 17/18 | Rows: 165
SH.STA.MMRT | Page 18/18 | Rows: 88
Fetching indicator: SH.MED.PHYS.ZS
SH.MED.PHYS.ZS | Page 1/18 | Rows: 175
SH.MED.PHYS.ZS | Page 2/18 | Rows: 166
SH.MED.PHYS.ZS | Page 3/18 | Rows: 165
SH.MED.PHYS.ZS | Page 4/18 | Rows: 165
SH.MED.PHYS.ZS | Page 5/18 | Rows: 165
SH.MED.PHYS.ZS | Page 6/18 | Rows: 165
SH.MED.PHYS.ZS | Page 7/18 | Rows: 169
SH.MED.PHYS.ZS | Page 8/18 | Rows: 172
SH.MED.PHYS.ZS | Page 9/18 | Rows: 165
SH.MED.PHYS.ZS | Page 10/18 | Rows: 165
SH.MED.PHYS.ZS | Page 11/18 | Rows: 165
SH.MED.PHYS.ZS | Page 12/18 | Rows: 165
SH.MED.PHYS.ZS | Page 13/18 | Rows: 165
SH.MED.PHYS.ZS | Page 14/18 | Rows: 173
SH.MED.PHYS.ZS | Page 15/18 | Rows: 168
SH.MED.PHYS.ZS | Page 16/18 | Rows: 165
SH.MED.PHYS.ZS | Page 17/18 | Rows: 165
SH.MED.PHYS.ZS | Page 18/18 | Rows: 88
Fetching indicator: SH.IMM.MEAS
SH.IMM.MEAS | Page 1/18 | Rows: 175
SH.IMM.MEAS | Page 2/18 | Rows: 166
SH.IMM.MEAS | Page 3/18 | Rows: 165
SH.IMM.MEAS | Page 4/18 | Rows: 165
SH.IMM.MEAS | Page 5/18 | Rows: 165
SH.IMM.MEAS | Page 6/18 | Rows: 165
SH.IMM.MEAS | Page 7/18 | Rows: 169
SH.IMM.MEAS | Page 8/18 | Rows: 172
SH.IMM.MEAS | Page 9/18 | Rows: 165
SH.IMM.MEAS | Page 10/18 | Rows: 165
SH.IMM.MEAS | Page 11/18 | Rows: 165
SH.IMM.MEAS | Page 12/18 | Rows: 165
SH.IMM.MEAS | Page 13/18 | Rows: 165
SH.IMM.MEAS | Page 14/18 | Rows: 173
SH.IMM.MEAS | Page 15/18 | Rows: 168
SH.IMM.MEAS | Page 16/18 | Rows: 165
SH.IMM.MEAS | Page 17/18 | Rows: 165
SH.IMM.MEAS | Page 18/18 | Rows: 88
health -> 14630 total rows collected

Fetching category: environment
Fetching indicator: EN.ATM.CO2E.PC
No data found for EN.ATM.CO2E.PC
Fetching indicator: AG.LND.FRST.ZS
AG.LND.FRST.ZS | Page 1/18 | Rows: 175
AG.LND.FRST.ZS | Page 2/18 | Rows: 166
AG.LND.FRST.ZS | Page 3/18 | Rows: 165
AG.LND.FRST.ZS | Page 4/18 | Rows: 165
AG.LND.FRST.ZS | Page 5/18 | Rows: 165
AG.LND.FRST.ZS | Page 6/18 | Rows: 165
AG.LND.FRST.ZS | Page 7/18 | Rows: 169
AG.LND.FRST.ZS | Page 8/18 | Rows: 172
AG.LND.FRST.ZS | Page 9/18 | Rows: 165
AG.LND.FRST.ZS | Page 10/18 | Rows: 165
AG.LND.FRST.ZS | Page 11/18 | Rows: 165
AG.LND.FRST.ZS | Page 12/18 | Rows: 165
AG.LND.FRST.ZS | Page 13/18 | Rows: 165
AG.LND.FRST.ZS | Page 14/18 | Rows: 173
AG.LND.FRST.ZS | Page 15/18 | Rows: 168
AG.LND.FRST.ZS | Page 16/18 | Rows: 165
AG.LND.FRST.ZS | Page 17/18 | Rows: 165
AG.LND.FRST.ZS | Page 18/18 | Rows: 88
Fetching indicator: EG.USE.PCAP.KG.OE
EG.USE.PCAP.KG.OE | Page 1/18 | Rows: 175
EG.USE.PCAP.KG.OE | Page 2/18 | Rows: 166
EG.USE.PCAP.KG.OE | Page 3/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 4/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 5/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 6/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 7/18 | Rows: 169
EG.USE.PCAP.KG.OE | Page 8/18 | Rows: 172
EG.USE.PCAP.KG.OE | Page 9/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 10/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 11/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 12/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 13/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 14/18 | Rows: 173
EG.USE.PCAP.KG.OE | Page 15/18 | Rows: 168
EG.USE.PCAP.KG.OE | Page 16/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 17/18 | Rows: 165
EG.USE.PCAP.KG.OE | Page 18/18 | Rows: 88
Fetching indicator: EG.ELC.ACCS.ZS
EG.ELC.ACCS.ZS | Page 1/18 | Rows: 175
EG.ELC.ACCS.ZS | Page 2/18 | Rows: 166
EG.ELC.ACCS.ZS | Page 3/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 4/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 5/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 6/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 7/18 | Rows: 169
EG.ELC.ACCS.ZS | Page 8/18 | Rows: 172
EG.ELC.ACCS.ZS | Page 9/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 10/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 11/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 12/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 13/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 14/18 | Rows: 173
EG.ELC.ACCS.ZS | Page 15/18 | Rows: 168
EG.ELC.ACCS.ZS | Page 16/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 17/18 | Rows: 165
EG.ELC.ACCS.ZS | Page 18/18 | Rows: 88
Fetching indicator: ER.H2O.INTR.PC
ER.H2O.INTR.PC | Page 1/18 | Rows: 175
ER.H2O.INTR.PC | Page 2/18 | Rows: 166
ER.H2O.INTR.PC | Page 3/18 | Rows: 165
ER.H2O.INTR.PC | Page 4/18 | Rows: 165
ER.H2O.INTR.PC | Page 5/18 | Rows: 165
ER.H2O.INTR.PC | Page 6/18 | Rows: 165
ER.H2O.INTR.PC | Page 7/18 | Rows: 169
ER.H2O.INTR.PC | Page 8/18 | Rows: 172
ER.H2O.INTR.PC | Page 9/18 | Rows: 165
ER.H2O.INTR.PC | Page 10/18 | Rows: 165
ER.H2O.INTR.PC | Page 11/18 | Rows: 165
ER.H2O.INTR.PC | Page 12/18 | Rows: 165
ER.H2O.INTR.PC | Page 13/18 | Rows: 165
ER.H2O.INTR.PC | Page 14/18 | Rows: 173
ER.H2O.INTR.PC | Page 15/18 | Rows: 168
ER.H2O.INTR.PC | Page 16/18 | Rows: 165
ER.H2O.INTR.PC | Page 17/18 | Rows: 165
ER.H2O.INTR.PC | Page 18/18 | Rows: 88
environment -> 11704 total rows collected

Fetching category: technology
Fetching indicator: IT.NET.USER.ZS
IT.NET.USER.ZS | Page 1/18 | Rows: 175
IT.NET.USER.ZS | Page 2/18 | Rows: 166
IT.NET.USER.ZS | Page 3/18 | Rows: 165
IT.NET.USER.ZS | Page 4/18 | Rows: 165
IT.NET.USER.ZS | Page 5/18 | Rows: 165
IT.NET.USER.ZS | Page 6/18 | Rows: 165
IT.NET.USER.ZS | Page 7/18 | Rows: 169
IT.NET.USER.ZS | Page 8/18 | Rows: 172
IT.NET.USER.ZS | Page 9/18 | Rows: 165
IT.NET.USER.ZS | Page 10/18 | Rows: 165
IT.NET.USER.ZS | Page 11/18 | Rows: 165
IT.NET.USER.ZS | Page 12/18 | Rows: 165
IT.NET.USER.ZS | Page 13/18 | Rows: 165
IT.NET.USER.ZS | Page 14/18 | Rows: 173
IT.NET.USER.ZS | Page 15/18 | Rows: 168
IT.NET.USER.ZS | Page 16/18 | Rows: 165
IT.NET.USER.ZS | Page 17/18 | Rows: 165
IT.NET.USER.ZS | Page 18/18 | Rows: 88
Fetching indicator: IT.CEL.SETS.P2
IT.CEL.SETS.P2 | Page 1/18 | Rows: 175
IT.CEL.SETS.P2 | Page 2/18 | Rows: 166
IT.CEL.SETS.P2 | Page 3/18 | Rows: 165
IT.CEL.SETS.P2 | Page 4/18 | Rows: 165
IT.CEL.SETS.P2 | Page 5/18 | Rows: 165
IT.CEL.SETS.P2 | Page 6/18 | Rows: 165
IT.CEL.SETS.P2 | Page 7/18 | Rows: 169
IT.CEL.SETS.P2 | Page 8/18 | Rows: 172
IT.CEL.SETS.P2 | Page 9/18 | Rows: 165
IT.CEL.SETS.P2 | Page 10/18 | Rows: 165
IT.CEL.SETS.P2 | Page 11/18 | Rows: 165
IT.CEL.SETS.P2 | Page 12/18 | Rows: 165
IT.CEL.SETS.P2 | Page 13/18 | Rows: 165
IT.CEL.SETS.P2 | Page 14/18 | Rows: 173
IT.CEL.SETS.P2 | Page 15/18 | Rows: 168
IT.CEL.SETS.P2 | Page 16/18 | Rows: 165
IT.CEL.SETS.P2 | Page 17/18 | Rows: 165
IT.CEL.SETS.P2 | Page 18/18 | Rows: 88
Fetching indicator: IT.NET.BBND.P2
IT.NET.BBND.P2 | Page 1/18 | Rows: 175
IT.NET.BBND.P2 | Page 2/18 | Rows: 166
IT.NET.BBND.P2 | Page 3/18 | Rows: 165
IT.NET.BBND.P2 | Page 4/18 | Rows: 165
IT.NET.BBND.P2 | Page 5/18 | Rows: 165
IT.NET.BBND.P2 | Page 6/18 | Rows: 165
IT.NET.BBND.P2 | Page 7/18 | Rows: 169
IT.NET.BBND.P2 | Page 8/18 | Rows: 172
IT.NET.BBND.P2 | Page 9/18 | Rows: 165
IT.NET.BBND.P2 | Page 10/18 | Rows: 165
IT.NET.BBND.P2 | Page 11/18 | Rows: 165
IT.NET.BBND.P2 | Page 12/18 | Rows: 165
IT.NET.BBND.P2 | Page 13/18 | Rows: 165
IT.NET.BBND.P2 | Page 14/18 | Rows: 173
IT.NET.BBND.P2 | Page 15/18 | Rows: 168
IT.NET.BBND.P2 | Page 16/18 | Rows: 165
IT.NET.BBND.P2 | Page 17/18 | Rows: 165
IT.NET.BBND.P2 | Page 18/18 | Rows: 88
Fetching indicator: IT.NET.SECR.P6
IT.NET.SECR.P6 | Page 1/18 | Rows: 175
IT.NET.SECR.P6 | Page 2/18 | Rows: 166
IT.NET.SECR.P6 | Page 3/18 | Rows: 165
IT.NET.SECR.P6 | Page 4/18 | Rows: 165
IT.NET.SECR.P6 | Page 5/18 | Rows: 165
IT.NET.SECR.P6 | Page 6/18 | Rows: 165
IT.NET.SECR.P6 | Page 7/18 | Rows: 169
IT.NET.SECR.P6 | Page 8/18 | Rows: 172
IT.NET.SECR.P6 | Page 9/18 | Rows: 165
IT.NET.SECR.P6 | Page 10/18 | Rows: 165
IT.NET.SECR.P6 | Page 11/18 | Rows: 165
IT.NET.SECR.P6 | Page 12/18 | Rows: 165
IT.NET.SECR.P6 | Page 13/18 | Rows: 165
IT.NET.SECR.P6 | Page 14/18 | Rows: 173
IT.NET.SECR.P6 | Page 15/18 | Rows: 168
IT.NET.SECR.P6 | Page 16/18 | Rows: 165
IT.NET.SECR.P6 | Page 17/18 | Rows: 165
IT.NET.SECR.P6 | Page 18/18 | Rows: 88
Fetching indicator: IP.JRN.ARTC.SC
IP.JRN.ARTC.SC | Page 1/18 | Rows: 175
IP.JRN.ARTC.SC | Page 2/18 | Rows: 166
IP.JRN.ARTC.SC | Page 3/18 | Rows: 165
IP.JRN.ARTC.SC | Page 4/18 | Rows: 165
IP.JRN.ARTC.SC | Page 5/18 | Rows: 165
IP.JRN.ARTC.SC | Page 6/18 | Rows: 165
IP.JRN.ARTC.SC | Page 7/18 | Rows: 169
IP.JRN.ARTC.SC | Page 8/18 | Rows: 172
IP.JRN.ARTC.SC | Page 9/18 | Rows: 165
IP.JRN.ARTC.SC | Page 10/18 | Rows: 165
IP.JRN.ARTC.SC | Page 11/18 | Rows: 165
IP.JRN.ARTC.SC | Page 12/18 | Rows: 165
IP.JRN.ARTC.SC | Page 13/18 | Rows: 165
IP.JRN.ARTC.SC | Page 14/18 | Rows: 173
IP.JRN.ARTC.SC | Page 15/18 | Rows: 168
IP.JRN.ARTC.SC | Page 16/18 | Rows: 165
IP.JRN.ARTC.SC | Page 17/18 | Rows: 165
IP.JRN.ARTC.SC | Page 18/18 | Rows: 88
technology -> 14630 total rows collected

In [93]:
print(category_dataframes.keys())

dict_keys(['population', 'economy', 'education', 'health', 'environment', 'technology'])

In [94]:
for key, df in category_dataframes.items():
    print(key, df.shape)

population (14630, 7)
economy (14630, 7)
education (14630, 7)
health (14630, 7)
environment (11704, 7)
technology (14630, 7)

In [95]:
population_df = category_dataframes.get("population", pd.DataFrame())
economy_df = category_dataframes.get("economy", pd.DataFrame())
education_df = category_dataframes.get("education", pd.DataFrame())
health_df = category_dataframes.get("health", pd.DataFrame())
environment_df = category_dataframes.get("environment", pd.DataFrame())
technology_df = category_dataframes.get("technology", pd.DataFrame())

In [96]:
economy_df.head()

,country_code,country_name,iso3_code,indicator_code,indicator_name,year,indicator_value
0,ZH,Africa Eastern and Southern,AFE,NY.GDP.MKTP.CD,GDP (current US$),2025,NaN
1,ZH,Africa Eastern and Southern,AFE,NY.GDP.MKTP.CD,GDP (current US$),2024,1.242694e+12
2,ZH,Africa Eastern and Southern,AFE,NY.GDP.MKTP.CD,GDP (current US$),2023,1.179359e+12
3,ZH,Africa Eastern and Southern,AFE,NY.GDP.MKTP.CD,GDP (current US$),2022,1.228968e+12
4,ZH,Africa Eastern and Southern,AFE,NY.GDP.MKTP.CD,GDP (current US$),2021,1.114145e+12

In [97]:
countries_df

,id,iso2Code,name,region,incomeLevel,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,High income,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,Aggregates,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,Aggregates,,
4,AFW,ZI,Africa Western and Central,Aggregates,Aggregates,,
...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,Aggregates,,
292,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan",Low income,44.2075,15.352
293,ZAF,ZA,South Africa,Sub-Saharan Africa,Upper middle income,28.1871,-25.746
294,ZMB,ZM,Zambia,Sub-Saharan Africa,Lower middle income,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312

In [98]:
economy_df["iso3_code"].head()

0    AFE
1    AFE
2    AFE
3    AFE
4    AFE
Name: iso3_code, dtype: object

In [99]:
countries_df["id"].head()

0    ABW
1    AFE
2    AFG
3    AFR
4    AFW
Name: id, dtype: object

In [100]:
economy_df.rename(
    columns={"iso3_code": "id"},
    inplace=True
)

In [102]:
merged_dataframes = {}

for category, df in category_dataframes.items():

    temp_df = df.rename(
        columns={"iso3_code": "id"}
    )

    merged_df = pd.merge(
        temp_df,
        countries_df,
        on="id",
        how="inner"
    )

    merged_dataframes[category] = merged_df

    print(f"{category}: {merged_df.shape}")

population: (14355, 13)
economy: (14355, 13)
education: (14355, 13)
health: (14355, 13)
environment: (11484, 13)
technology: (14355, 13)

In [103]:
population_final = merged_dataframes["population"]

economy_final = merged_dataframes["economy"]

education_final = merged_dataframes["education"]

health_final = merged_dataframes["health"]

environment_final = merged_dataframes["environment"]

technology_final = merged_dataframes["technology"]

In [104]:
economy_final.columns

Index(['country_code', 'country_name', 'id', 'indicator_code',
       'indicator_name', 'year', 'indicator_value', 'iso2Code', 'name',
       'region', 'incomeLevel', 'longitude', 'latitude'],
      dtype='object')

In [105]:
for category, df in merged_dataframes.items():

    cols_to_drop = [
        "country_code",
        "name"
    ]

    existing_cols = [
        col for col in cols_to_drop
        if col in df.columns
    ]

    df.drop(
        columns=existing_cols,
        inplace=True
    )

    print(
        f"{category}: {df.shape}"
    )

population: (14355, 11)
economy: (14355, 11)
education: (14355, 11)
health: (14355, 11)
environment: (11484, 11)
technology: (14355, 11)

In [106]:
for category, df in merged_dataframes.items():

    merged_dataframes[category] = df[
        df["incomeLevel"] != "Aggregates"
    ]

In [107]:
population_final = merged_dataframes["population"]

economy_final = merged_dataframes["economy"]

education_final = merged_dataframes["education"]

health_final = merged_dataframes["health"]

environment_final = merged_dataframes["environment"]

technology_final = merged_dataframes["technology"]

In [108]:
import os

os.makedirs(
    "world_bank_data",
    exist_ok=True
)

for category, df in merged_dataframes.items():

    df.to_csv(
        f"world_bank_data/{category}.csv",
        index=False
    )

print("All files saved successfully.")

All files saved successfully.

In [109]:
for category, df in merged_dataframes.items():

    print(f"\n{category}:")
    
    for col in df.columns:
        print(f" - {col}")

population:
 - country_name
 - id
 - indicator_code
 - indicator_name
 - year
 - indicator_value
 - iso2Code
 - region
 - incomeLevel
 - longitude
 - latitude

economy:
 - country_name
 - id
 - indicator_code
 - indicator_name
 - year
 - indicator_value
 - iso2Code
 - region
 - incomeLevel
 - longitude
 - latitude

education:
 - country_name
 - id
 - indicator_code
 - indicator_name
 - year
 - indicator_value
 - iso2Code
 - region
 - incomeLevel
 - longitude
 - latitude

health:
 - country_name
 - id
 - indicator_code
 - indicator_name
 - year
 - indicator_value
 - iso2Code
 - region
 - incomeLevel
 - longitude
 - latitude

environment:
 - country_name
 - id
 - indicator_code
 - indicator_name
 - year
 - indicator_value
 - iso2Code
 - region
 - incomeLevel
 - longitude
 - latitude

technology:
 - country_name
 - id
 - indicator_code
 - indicator_name
 - year
 - indicator_value
 - iso2Code
 - region
 - incomeLevel
 - longitude
 - latitude